In [99]:
# parameters
d = 0.75

In [100]:
import numpy as np

LinkMatrix = np.matrix(( (0.0, 0.0, 1.0, 0.0, 0.0, 0.0), 
                         (0.5, 0.0, 0.5, 0.0, 0.0, 0.0), 
                         (0.0, 0.0, 0.0, 0.5, 0.5, 0.0),
                         (0.0, 0.0, 0.0, 0.0, 1.0, 0.0), 
                         (0.0, 1.0, 0.0, 0.0, 0.0, 0.0), 
                         (0.0, 0.0, 0.0, 0.0, 1.0, 0.0)))  

In [101]:
Teleport = np.matrix(( (1./6, 1./6, 1./6, 1./6, 1./6, 1./6),
                       (1./6, 1./6, 1./6, 1./6, 1./6, 1./6),
                       (1./6, 1./6, 1./6, 1./6, 1./6, 1./6),
                       (1./6, 1./6, 1./6, 1./6, 1./6, 1./6),
                       (1./6, 1./6, 1./6, 1./6, 1./6, 1./6),
                       (1./6, 1./6, 1./6, 1./6, 1./6, 1./6) ))

In [102]:
T = np.add (d * LinkMatrix, (1-d) * Teleport)
print T

[[0.04166667 0.04166667 0.79166667 0.04166667 0.04166667 0.04166667]
 [0.41666667 0.04166667 0.41666667 0.04166667 0.04166667 0.04166667]
 [0.04166667 0.04166667 0.04166667 0.41666667 0.41666667 0.04166667]
 [0.04166667 0.04166667 0.04166667 0.04166667 0.79166667 0.04166667]
 [0.04166667 0.79166667 0.04166667 0.04166667 0.04166667 0.04166667]
 [0.04166667 0.04166667 0.04166667 0.04166667 0.79166667 0.04166667]]


In [103]:
x = [0.1, 0.1, 0.2, 0.3, 0.1, 0.2]

In [104]:
x_new = x*T
print x_new
x = x_new

[[0.07916667 0.11666667 0.15416667 0.11666667 0.49166667 0.04166667]]


[[0.1278135  0.22999909 0.22370046 0.12563996 0.25118032 0.04166667]]
[[0.12780929 0.22929607 0.22420761 0.12589919 0.25112117 0.04166667]]
[[0.12776753 0.23043212 0.22334958 0.12550962 0.25127449 0.04166667]]


In [105]:
SportsTeleport = np.matrix(( (0.4, 0.4, 0.05, 0.05, 0.05, 0.05),
                             (1., 0., 0., 0., 0., 0.),
                             (1., 0., 0., 0., 0., 0.),
                             (1., 0., 0., 0., 0., 0.),
                             (1., 0., 0., 0., 0., 0.),
                             (1., 0., 0., 0., 0., 0.) ))

T_sports = np.add (d * LinkMatrix, (1-d) * SportsTeleport)
print T_sports

[[0.25  0.    0.75  0.    0.    0.   ]
 [0.625 0.    0.375 0.    0.    0.   ]
 [0.25  0.    0.    0.375 0.375 0.   ]
 [0.25  0.    0.    0.    0.75  0.   ]
 [0.25  0.75  0.    0.    0.    0.   ]
 [0.25  0.    0.    0.    0.75  0.   ]]


In [106]:
x_sports = [0.2, 0.2, 0.2, 0.2, 0.1, 0.1]

In [109]:
x_sports_new = x_sports*T_sports
print x_sports_new
x = x_sports_new

[[0.325 0.075 0.225 0.075 0.3   0.   ]]
